name: generate artwork

on: push

jobs:
    generate_artwork:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
              
        - name: change script permission
          run: chmod +x ascii-script.sh

        - name: run shell script
          run: ./ascii-script.sh
