name: install ascii artwork

on: push

jobs:
    install:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install ascii artwork
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay program
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Test file exists
        run: grep -i "dragon" dragon.txt
        
      - name: Read File
        run: cat dragon.txt

      - name: list repo files
        run: ls -ltra