name: filters and activities workflow

on:
    workflow_dispatch:
    push:
        branches: 
        - main
        - '!feature/*'

    pull_request:
        types:
        - opened
        - closed
        paths-ignore:
        - Readme.md
        branches:
        - main    

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: echo event type
          run: echo "This workflow is executed on event type ${{github.event_name}}"
