
## setting variable and secret at step level
name: Exploring variables and secrets

on: push

jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
     - name: docker build
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx

       run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
   
     - name: Docker login
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         DOCKER_PASSWORD: s3cUrePaSsw0rd
       run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}

     - name: Docker publish
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx
       run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
   
   deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        env:       
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx
        run: echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest   
   