
## setting variable and secret at step level
name: Exploring variables and secrets

on: push

jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
     - name: docker build
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx

       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
   
     - name: Docker login
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         DOCKER_PASSWORD: s3cUrePaSsw0rd
       run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

     - name: Docker publish
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx
       run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
   
   deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        env:       
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: siddharth1
         IMAGE_NAME: github-actions-nginx
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest   
   